config/routes.rb
Rails.application.routes.draw do

  resources :users
  resources :flights
  resources :airplanes
  resources :reservations

  root 'session#new'

  get "/login" => 'session#new', :as => 'login'
  post "/login" => 'session#create'
  delete "/logout" => 'session#destroy', :as => 'logout'

  get '/search' => 'pages#search', :as => 'flightSearch'

  get '/reserveseat' => 'pages#reserveseat', :as => 'reserveseat'

  get '/flight/:id' => 'pages#flight'
  get '/flight' => 'pages#flight'

end

app/models/flight.rb
class Flight < ActiveRecord::Base
  belongs_to :airplane
  has_many :reservations
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  before_action :authenticate, only: [:new]
  before_action :set_flight, only: [:show, :edit, :update, :destroy]

  # GET /flights
  # GET /flights.json
  def index
    @flights = Flight.all
  end

  # GET /flights/1
  # GET /flights/1.json
  def show
  end

  # GET /flights/new
  def new
    @flight = Flight.new
    @airplanes = Airplane.all
  end

  # GET /flights/1/edit
  def edit
    @airplanes = Airplane.all
  end

  # POST /flights
  # POST /flights.json
  def create
    @flight = Flight.new(flight_params)

    respond_to do |format|
      if @flight.save
        format.html { redirect_to @flight, notice: 'Flight was successfully created.' }
        format.json { render :show, status: :created, location: @flight }
      else
        format.html { render :new }
        format.json { render json: @flight.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /flights/1
  # PATCH/PUT /flights/1.json
  def update
    respond_to do |format|
      if @flight.update(flight_params)
        format.html { redirect_to @flight, notice: 'Flight was successfully updated.' }
        format.json { render :show, status: :ok, location: @flight }
      else
        format.html { render :edit }
        format.json { render json: @flight.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /flights/1
  # DELETE /flights/1.json
  def destroy
    @flight.destroy
    respond_to do |format|
      format.html { redirect_to flights_url, notice: 'Flight was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_flight
      @flight = Flight.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def flight_params
      params.require(:flight).permit(:flightNum, :date, :to, :from, :airplane_id)
    end

    def authenticate
      redirect_to '/search' unless @current_user && @current_user.admin
    end
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/views/flights/_form.html.erb
<%= form_for(@flight) do |f| %>
  <% if @flight.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@flight.errors.count, "error") %> prohibited this flight from being saved:</h2>

      <ul>
      <% @flight.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <form class="col s12">
      <div class="row">
        <div class="input-field col s4 offset-s2">
          <%= f.label :flightNum %>
          <%= f.text_field :flightNum %>
        </div>
        <div class="input-field col s4">
          <%= f.label :date %>
          <%= f.date_field :date, class: "datepicker"%>
        </div>
      </div>
      <div class="row">
        <div class="input-field col s4 offset-s2">
          <%= f.label :from %>
          <%= f.text_field :from %>
        </div>
        <div class="input-field col s4">
          <%= f.label :to %>
          <%= f.text_field :to %>
        </div>
      </div>
      <div class="row">
        <div class="input-field col s8 offset-s2">
          <% airplane_arr = [] %>
          <% @airplanes.each do |a| %>
            <% x = [a.name, a.id] %>
            <% airplane_arr.push x %>
          <% end %>
          <%= f.label :airplane_id %><br>
          <%= f.select( :airplane_id, airplane_arr, {}, {:multiple => false}) %>

          <!-- <%= f.label :airplane_id %><br>
          <%= f.number_field :airplane_id %> -->
        </div>
      </div>
      <div class="row">
        <div class="col s8 offset-s2">
          <%= f.submit class: 'btn waves-effect waves-light' %>
        </div>
      </div>
    </form>
  </div>

<% end %>

app/views/flights/edit.html.erb
<h1>Editing Flight</h1>

<%= render 'form' %>

<%= link_to 'Show', @flight %> |
<%= link_to 'Back', flights_path %>

app/views/flights/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Flights</h1>

<div class="row">
  <div class="col s8 offset-s2">

    <table class="highlight striped">
      <thead>
        <tr>
          <th>Flightnum</th>
          <th>Date</th>
          <th>To</th>
          <th>From</th>
          <th>Airplane</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @flights.each do |flight| %>
          <tr>
            <td><%= flight.flightNum %></td>
            <td><%= flight.date %></td>
            <td><%= flight.to %></td>
            <td><%= flight.from %></td>
            <td><%= flight.airplane_id %></td>
            <td><%= link_to 'Show', flight %></td>
            <td><%= link_to 'Edit', edit_flight_path(flight) %></td>
            <td><%= link_to 'Destroy', flight, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>
<div class="row">
  <div class="col s8 offset-s2">
    <%= link_to 'New Flight', new_flight_path, class: 'waves-effect waves-light btn' %>
  </div>
</div>

app/views/flights/new.html.erb
<h1>New Flight</h1>

<%= render 'form' %>

<div class="row">
  <div class="col s8 offset-s2">
    <%= link_to 'Back', flights_path, class: 'waves-effect waves-light btn blue' %>
  </div>
</div>

app/views/flights/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Flightnum:</strong>
  <%= @flight.flightNum %>
</p>

<p>
  <strong>Date:</strong>
  <%= @flight.date %>
</p>

<p>
  <strong>To:</strong>
  <%= @flight.to %>
</p>

<p>
  <strong>From:</strong>
  <%= @flight.from %>
</p>

<p>
  <strong>Airplane:</strong>
  <%= @flight.airplane_id %>
</p>

<%= link_to 'Edit', edit_flight_path(@flight) %> |
<%= link_to 'Back', flights_path %>