config/routes.rb
Rails.application.routes.draw do

  resources :users
  resources :flights
  resources :airplanes
  resources :reservations

  root 'session#new'

  get "/login" => 'session#new', :as => 'login'
  post "/login" => 'session#create'
  delete "/logout" => 'session#destroy', :as => 'logout'

  get '/search' => 'pages#search', :as => 'flightSearch'

  get '/reserveseat' => 'pages#reserveseat', :as => 'reserveseat'

  get '/flight/:id' => 'pages#flight'
  get '/flight' => 'pages#flight'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0"/>
  <title>Burning Airlines</title>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link href='https://fonts.googleapis.com/css?family=Roboto:400,300,100,500' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="light-blue lighten-1" role="navigation">
    <div class="nav-wrapper container"><a id="logo-container" href="/search" class="brand-logo">Burning Airlines</a>
      <ul class="right hide-on-med-and-down">
        <% if @current_user && @current_user.admin %>
          <li><a href="<%= new_airplane_path %>">New Airplane</a></li>
          <li><a href="<%= new_flight_path %>">New Flight</a></li>
        <% end %>
        <% if @current_user %>
          <li><a href="/search">Search</a></li>
          <li><a href="/reservations">Reservations</a></li>
          <li><%= link_to "Logout", logout_path, :method => :delete %></li>
        <% else %>
          <li><a href="<%= new_user_path %>">Sign up</a></li>
          <li><a href="<%= login_path %>">Login</a></li>
        <% end %>
      </ul>

      <ul id="nav-mobile" class="side-nav">
        <% if @current_user && @current_user.admin %>
          <li><a href="<%= new_airplane_path %>">New Airplane</a></li>
          <li><a href="<%= new_flight_path %>">New Flight</a></li>
        <% end %>
        <% if @current_user %>
          <li><a href="/search">Search</a></li>
          <li><a href="/reservations">Reservations</a></li>
          <li><%= link_to "Logout", logout_path, :method => :delete %></li>
        <% else %>
          <li><a href="<%= new_user_path %>">Sign up</a></li>
          <li><a href="<%= login_path %>">Login</a></li>
        <% end %>
      </ul>
      <a href="#" data-activates="nav-mobile" class="button-collapse"><i class="material-icons">menu</i></a>
    </div>
  </nav>

  <div class="row blue">
    <div class="col s12 white-text" style="text-align:center">
      <%= flash[:error] %>
    </div>
  </div>

  <%= yield %>

</body>
</html>